# Numpy : package for Multi deminensional array !

In [1]:
import numpy as np

In [2]:
simple_list=[28,12,7]
np.array(simple_list)

array([28, 12,  7])

In [4]:
arr=np.array([28,12,7])
arr

array([28, 12,  7])

In [6]:
list_to_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_to_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(7,18)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

In [17]:
np.arange(5,55,5) #  5 Table 

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [16]:
np.arange(0,51) #creating whole numbers upto 50 !

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
np.arange(28) #default start value is '0'

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [24]:
np.zeros(10) # default as float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((10),int) # int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((7),int)

array([1, 1, 1, 1, 1, 1, 1])

In [31]:
np.ones((2,7),int)  #rows and colums

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [34]:
np.linspace(0,5,5)  #front

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [46]:
np.linspace(4,2,5) #backward

array([4. , 3.5, 3. , 2.5, 2. ])

In [52]:
np.eye((10),dtype=int) #identity matrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [53]:
np.random.rand(2,5)

array([[0.23063205, 0.47974176, 0.92434507, 0.6418526 , 0.76144131],
       [0.13446829, 0.35450096, 0.10740388, 0.63540859, 0.14251574]])

In [54]:
np.random.randn(2,4)

array([[ 0.56395534, -1.00661185, -0.11996067,  0.41626162],
       [-0.09610002, -0.72770329, -0.12873565,  1.41878148]])

In [59]:
np.random.randint(2,8) # reflects - 2,3,4,5,6,7 except = 8

3

In [61]:
np.random.randint(1,17,17) # 17 outputs expect 17

array([13,  7,  7, 10, 12,  8,  4, 13,  4, 15,  4, 13,  8,  7,  8, 14,  3])

In [70]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
sample_array.reshape(5,6) # 5-rows , 6- columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [77]:
rand_array=np.random.randint(0,100,20)
rand_array

array([26, 45, 24, 65, 34, 12, 30, 71, 73,  6, 43, 52, 26, 54, 91, 75, 79,
       27, 83, 85])

In [80]:
rand_array.max()

91

In [81]:
rand_array.min()

6

In [85]:
s=np.eye((10),dtype=int)
s

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [92]:
s.T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [94]:
s=np.random.rand(2,3)
s

array([[0.17714303, 0.33021172, 0.1088056 ],
       [0.69272865, 0.51552998, 0.12135823]])

In [95]:
s.T # transpose = T

array([[0.17714303, 0.69272865],
       [0.33021172, 0.51552998],
       [0.1088056 , 0.12135823]])

In [101]:
simple_array=np.arange(11,29)
simple_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28])

In [102]:
simple_array[8]

19

In [100]:
rand_array[8]

73

In [103]:
sample_array[2:5]

array([2, 3, 4])

In [104]:
sample_array[1:4]=100
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])


# Two Deminsional Array 

In [107]:
import numpy as np

In [108]:
sample_matrix=np.array(([2,3,4],[45,21,3],[44,55,2]))
sample_matrix

array([[ 2,  3,  4],
       [45, 21,  3],
       [44, 55,  2]])

In [113]:
sample_matrix[1:2]

array([[45, 21,  3]])

In [115]:
sample_matrix[1,1]

21

In [116]:
sample_matrix[2:]

array([[44, 55,  2]])

In [119]:
sample_matrix[0:]

array([[ 2,  3,  4],
       [45, 21,  3],
       [44, 55,  2]])

 
# Selecting Techniques 

In [120]:
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [122]:
sample_array+sample_array

array([  0, 200, 200, 200,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58])

In [123]:
np.log(sample_array)

C:\Users\Nikhil Sukthe\AppData\Local\Temp\ipykernel_7464\988743405.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array)


array([      -inf, 4.60517019, 4.60517019, 4.60517019, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [124]:
np.argmax(sample_array) # index of max and min 

1

In [126]:
np.argmin(sample_array)

0

In [127]:
np.max(sample_array)

100

In [128]:
np.min(sample_array)

0

In [129]:
np.sqrt(sample_array)

array([ 0.        , 10.        , 10.        , 10.        ,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481])

In [130]:
np.mean(sample_array) 

24.3

In [131]:
np.var(sample_array) #normal distribution

694.2100000000002

In [133]:
np.exp(rand_array)

array([1.95729609e+11, 3.49342711e+19, 2.64891221e+10, 1.69488924e+28,
       5.83461743e+14, 1.62754791e+05, 1.06864746e+13, 6.83767123e+30,
       5.05239363e+31, 4.03428793e+02, 4.72783947e+18, 3.83100800e+22,
       1.95729609e+11, 2.83075330e+23, 3.31740010e+39, 3.73324200e+32,
       2.03828107e+34, 5.32048241e+11, 1.11286375e+36, 8.22301271e+36])